version: '3.9'
services:

  database:
    container_name: database
    image: mysql
    expose:
      - 3307
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "fastpay"
      MYSQL_USER: "diseñoII"
      MYSQL_PASSWORD: "diseñoII"
    networks:
      - fastpay-network
    restart: unless-stopped
  
  security:
    depends_on:
      - database
    image: node:16.3.0
    build: 
      context: .
      dockerfile: dockerfile_security
    container_name: security_api
    volumes:
      - ./services/security-api:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - fastpay-network

networks:
  fastpay-network:
    name: fastpay-network


