
FROM node:latest
WORKDIR /app
COPY ./services/security-api/package*.json /app
COPY ./services/security-api/tsconfig.json /app
COPY ./services/security-api/src ./src
COPY ./services/security-api/*.env /app
COPY ./services/security-api/prisma ./prisma

RUN npm install
RUN npm run migrate

# Set up a default command
CMD [ "npm","start" ]